### ISSUE TITLE
Error: The store is not valid.

### ISSUE THREAD

**Issue by DeltaLikeM** [nfriedly/express-rate-limit#33]
So everything worked fine on the first run but after shutting the node server down and restarting it this error occured

Any idea how i can resolve this issue ?

```
// ensure that the store has the incr method
    if (typeof options.store.incr !== 'function' || typeof options.store.resetKey !== 'function') {
        throw new Error('The store is not valid.');
    }
```

```
Error: The store is not valid.
    at new RateLimit (/Users/deltam/git/project/node_modules/express-rate-limit/lib/express-rate-limit.js:38:15)
    at Object.<anonymous> (/Users/deltam/git/project/server.js:196:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by DeltaLikeM** [comment]
I found out that this issue occurs if I try to use the store a global rate and a rate for one api

**Comment by nfriedly** [comment]
oh, interesting. Can you show me your code (minus any passwords)?

**Comment by DeltaLikeM** [comment]
```js
var limiter = new RateLimit({
  windowMs: 15*60*1000, // 15 minutes
  max: 100, // limit each IP to 100 requests per windowMs
  delayMs: 0, // disable delaying - full speed until the max limit is reached
  store: new RedisStore({
            client: redis_client,
            expiry: 15*60*1000, 
            prefix: "rl"
        })
});

//  apply to all requests
app.use(limiter);

var createAccountLimiter = new RateLimit({
  windowMs: 60*60*1000, // 1 hour window
  delayAfter: 1, // begin slowing down responses after the first request
  delayMs: 3*1000, // slow down subsequent responses by 3 seconds per request
  max: 5, // start blocking after 5 requests
  message: "Too many accounts created from this IP, please try again after an hour"
  store: new RedisStore({
            client: redis_client,
            expiry: 60*60*1000, 
            prefix: "rl"
        })
});

app.post('/create-account', createAccountLimiter, function(req, res) {
 //...
});

```

it was a combination of the above, if i find time I'll create a complete example reproducing the issue if the one above is not working

**Comment by nfriedly** [comment]
I think having the same prefix for both redis store instances might cause hiccups, although I can't see how that would cause the error you logged.

It also looks like your setup is using both limiters for the `/create-account` endpoint.. but that also shouldn't cause the kind of trouble you're seeing.

I'm pretty stumped :/

**Comment by DeltaLikeM** [comment]
If it ever happen again I'll open a new one
Thank you very much for investigating
